version: 2

jobs:
  linux-swift-3:
    docker:
      - image: swift:3.1
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  linux-swift-4:
    docker:
      - image: swift:4.0
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  macOS-swift-4:
    macos:
      xcode: "9.0"
    steps:
      - run: sudo gem install xcpretty
      - run: brew update
      - run: brew tap vapor/tap
      - run: brew install ctls mysql
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme SwiftyBeaverProvider-Package -enableCodeCoverage YES test | xcpretty
      - run: bash <(curl -s https://codecov.io/bash)

  macOS-swift-3:
    macos:
      xcode: "8.3.3"
    steps:
      - run: sudo gem install xcpretty
      - run: brew update
      - run: brew tap vapor/tap
      - run: brew install ctls mysql
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme SwiftyBeaverProvider -enableCodeCoverage YES test | xcpretty

workflows:
  version: 2
  linux:
    jobs:
      - linux-swift-3
      - linux-swift-4
  macOS:
    jobs:
      - macOS-swift-3
      - macOS-swift-4